# podman-compose.yml
# 适用于Podman的战役推演系统配置
version: '3.8'

services:
  # API服务 - 赤壁之战战役推演
  mrzhuge-battle-api:
    image: mrzhuge-battle:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: mrzhuge-battle-api
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static:ro
      - ./src:/app/src:ro
      - ./knowledge_base:/app/knowledge_base:ro
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/battle/赤壁之战"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 战役推演前端服务 (Nginx)
  mrzhuge-frontend:
    image: nginx:alpine
    container_name: mrzhuge-battle-frontend
    ports:
      - "8080:80"
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx-battle.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mrzhuge-battle-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/battle-replay-leaflet.html"]
      interval: 30s
      timeout: 10s
      retries: 3

# 网络配置
networks:
  default:
    name: mrzhuge-battle-network
    driver: bridge

# 数据卷
volumes:
  mrzhuge_logs:
    driver: local
  mrzhuge_data:
    driver: local